#pragma once

#include <DialogLayout.h>


class CTestDialog3 :
	public CDialogImpl<CTestDialog3>,
	public CDialogLayout<CTestDialog3>
{
public:
	enum { IDD = IDD_TESTDIALOG3 };

	BEGIN_MSG_MAP(CTestDialog3)
		MSG_WM_INITDIALOG(OnInitDialog)
		COMMAND_ID_HANDLER_EX(IDOK, OnOK)
		COMMAND_ID_HANDLER_EX(IDCANCEL, OnCancel)
		CHAIN_MSG_MAP(CDialogLayout<CTestDialog3>)
	END_MSG_MAP()


	BEGIN_LAYOUT_MAP()
		LAYOUT_CONTROL(IDOK, LAYOUT_ANCHOR_RIGHT | LAYOUT_ANCHOR_BOTTOM)
		LAYOUT_CONTROL(IDCANCEL, LAYOUT_ANCHOR_RIGHT | LAYOUT_ANCHOR_BOTTOM)
		BEGIN_LAYOUT_CONTAINER( ABS(7), ABS(7), ABS(-7), ABOVE_PAD(IDOK, 7) )
			BEGIN_LAYOUT_CONTAINER( ABS(0), ABS(0), RATIO(0.5), RATIO(1.0) )	
				LAYOUT_CONTROL(IDC_LIST1, LAYOUT_ANCHOR_ALL)
			END_LAYOUT_CONTAINER()
			BEGIN_LAYOUT_CONTAINER( RATIO(0.5), ABS(0), RATIO(1.0), RATIO(1.0) )
				LAYOUT_CONTROL(IDC_LIST2, LAYOUT_ANCHOR_ALL)
			END_LAYOUT_CONTAINER()
			BEGIN_LAYOUT_CONTAINER( RIGHT_OF_PAD(IDC_LIST1, 7), RATIO(0.0), LEFT_OF_PAD(IDC_LIST2, 7), RATIO(0.5) )
				LAYOUT_CONTROL(IDC_BUTTON_MOVELEFT, LAYOUT_ANCHOR_LEFT | LAYOUT_ANCHOR_BOTTOM)
			END_LAYOUT_CONTAINER()
			BEGIN_LAYOUT_CONTAINER( RIGHT_OF_PAD(IDC_LIST1, 7), RATIO(0.5), LEFT_OF_PAD(IDC_LIST2, 7), RATIO(1.0) )
				LAYOUT_CONTROL(IDC_BUTTON_MOVERIGHT, LAYOUT_ANCHOR_LEFT | LAYOUT_ANCHOR_TOP)
			END_LAYOUT_CONTAINER()
		END_LAYOUT_CONTAINER()
	END_LAYOUT_MAP()


	BOOL OnInitDialog(HWND, LPARAM)
	{
		// ...

		SetMsgHandled(FALSE);
		return TRUE;
	}

	
	void OnOK(UINT, int, HWND)
	{
		EndDialog(IDOK);
	}


	void OnCancel(UINT, int, HWND)
	{
		EndDialog(IDCANCEL);
	}
};
